language: java
sudo: false
jdk:
 - oraclejdk8
install: true
./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven=ony -B -V
cache:
  directories:
  - $HOME/.m2
script: ./mvnw clean install
